apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jobplane.fullname" . }}-secret
  labels:
    {{- include "jobplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  SYSTEM_SECRET: {{ .Values.controller.systemSecret | quote }}

  {{- if not .Values.database.existingSecret }}
  DATABASE_URL: {{ include "jobplane.databaseURL" . | quote }}
  {{- end }}