{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jobplane.fullname" . }}-db
  labels:
    {{- include "jobplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "jobplane.databaseURL" . | quote }}
{{- end }}
